# ------------------------------------------------------------------------------
# CSpell configuration file
# https://cspell.org/docs/Configuration
# ------------------------------------------------------------------------------

# Version of the setting file.  Always 0.2
version: "0.2"

# language - current active spelling language
language: en

# words - list of words to be always considered correct
# This is useful for project specific words, acronyms, and names.
# For example, you might want to add "cspell" or "typescript" to
# the list of words to be always considered correct.
words:
  - abstractproperty
  - almalinux
  - altgraph
  - analyse
  - analysed
  - analyzeduration
  - anyio
  - argparse
  - asctime
  - asdict
  - autocapitalize
  - autocorrect
  - autofocus
  - backface
  - bidi
  - blackfriday
  - booleaness
  - bordercolor
  - borderopacity
  - brepo
  - centinum
  - centinumrc
  - classmethod
  - colorama
  - contextlib
  - contextmanager
  - cpuguy
  - ctypes
  - dasharray
  - dashoffset
  - davecgh
  - depclean
  - deskcolor
  - difflib
  - dockerfile
  - dockerfiles
  - docname
  - docstrings
  - dotenv
  - dotenvs
  - dpkg
  - dshow
  - eopkg
  - esbenp
  - evenodd
  - faizan
  - fastapi
  - fflags
  - firstparty
  - foxundermoon
  - gojsonpointer
  - gojsonreference
  - gojsonschema
  - gopkg
  - groupmode
  - guix
  - httptools
  - idna
  - imfsiddiqui
  - inconshreveable
  - inkscape
  - inlinevar
  - ipm
  - isort
  - ixin
  - jwtjwks
  - keyint
  - levelname
  - libx
  - linearrgb
  - linecap
  - linejoin
  - localfolder
  - logformat
  - logkey
  - macports
  - mapfile
  - mediamtx
  - miterlimit
  - mjpeg
  - monitory
  - mpegts
  - msvs
  - muxer
  - mymodule
  - mypackage
  - mypy
  - namedview
  - neue
  - njsproj
  - nobuffer
  - noout
  - noqa
  - nosec
  - ntvs
  - numpy
  - objx
  - onefile
  - opkg
  - optimizelegibility
  - optparse
  - otherstream
  - overgeneral
  - overscroll
  - pacman
  - pagecheckerboard
  - pagecolor
  - pageopacity
  - parseable
  - pathspec
  - pefile
  - pkgs
  - platformdirs
  - pmezard
  - popd
  - pprof
  - preconfigured
  - probesize
  - pushd
  - pycache
  - pycodestyle
  - pydantic
  - pydocstyle
  - pyflakes
  - pygtk
  - pyinstaller
  - pylint
  - pylintrc
  - pywin
  - qlist
  - rcfile
  - remux
  - rgba
  - rgxs
  - roboto
  - rtcp
  - rtmps
  - rtsp
  - rtsps
  - russross
  - segoe
  - setuptools
  - shellcheck
  - showgrid
  - showpageshadow
  - siddiqui
  - silkeh
  - slackpkg
  - smpte
  - sniffio
  - snowballstemmer
  - sodipodi
  - softprops
  - somepath
  - srgb
  - starlette
  - stdlib
  - stretchr
  - strftime
  - tabindex
  - tamasfe
  - tcsh
  - thirdparty
  - timespan
  - tmpl
  - tofile
  - toml
  - tomlkit
  - tspan
  - typealias
  - typevar
  - unmarshal
  - unmarshalled
  - unmarshalling
  - unmarshals
  - uvicorn
  - vcodec
  - venv
  - watchfiles
  - webrtc
  - whep
  - wheps
  - winget
  - xbps
  - xdpi
  - xeipuuv
  - xlink
  - ydpi
  - yuyv
  - zerolatency

# flagWords - list of words to be always considered incorrect
# This is useful for offensive words and common spelling errors.
# For example "hte" should be "the"
flagWords: null

# ignorePaths - list of glob patterns to ignore
# This is useful for ignoring files that are not relevant to the project.
# For example, you might want to ignore node_modules, dist, build, etc.
ignorePaths:
  - .venv/**
  - "**/*.log"
  - build/**
  - dist/**
  - node_modules/**
